config/routes.rb
Rails.application.routes.draw do
  # TODO: Should the root show worlds instead?
  # root 'worlds#show'

  root to: redirect('play')
  get 'play', to: 'worlds#show', as: 'play'

  get 'signup', to: 'users#new', as: 'signup'
  match 'login', to: 'sessions#create', as: 'login', via: %i[get post]
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'home', to: 'pages#home', as: 'home'

  resources :users
  resources :sessions

  get '/' => redirect('play')

  mount ActionCable.server => '/cable'
  # TODO: Work on below
  # match "/telnet" => TelnetSinatra
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :room

  # methods
#   move between rooms
#   broadcast messages to players in the rooms
#   get hit
#   hit things

  def move_to_room!(new_room)
    self.update room: new_room
  end

  # Will send a message to all players in a room.
  def send_message_to_room(room, msg)

  end

  # Send a message to all players in this room.
  def send_message_to_current_room(msg)
    players_in_room = Player.find_by_room_id @room_id
    players_in_room.each {|p| p.receive_message(msg)}
  end

  # TODO make a mixin for things that can get hit or attack

  def hit(damage)
    self.update hp: (@hp - damage.amount)
  end

  def attack(thing)
    # HARDCODED
    damage = 5
    thing.hit(Damage.new(:physical, damage))
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/damage.rb
class Damage
  attr_accessor :damage_type, :amount

  def initialize(type, amount)
    @damage_type = type
    @amount = amount
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model

  attr_accessor :channel, :string
  validates_presence_of :channel, :string
  # after_create_commit { MessageBroadcastJob.perform_later self }

  def initialize(attributes={})
    super
    # todo make this run in a job
    # return_strings = @user.parse_command(@string)
    msg = @string
    if msg.class == String
      ActionCable.server.broadcast @channel, { message: msg }
    elsif msg.class == Integer
      ActionCable.server.broadcast @channel, { message: msg.to_s }
    else
      msg.each do |line|
        ActionCable.server.broadcast @channel, { message: line }
      end
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates_presence_of :name, :room_id, :hp, :xp, :level, :user_id

  @@player_cmds = CommandSet.new

  def move_to(new_id)
    self.update_attribute(:room_id, new_id)
    self.send_message_to_self('moved to ' + Room.find(new_id).title)
  end

  def current_room
    Room.find(self.room_id)
  end

  def receive_message(msg)
    send_message_to_self(msg)
  end

  def send_message_to_self(msg)
    Message.new channel: "world_channel_#{self.user_id}", string: msg
  end

  def send_message_to_user(user_id, msg)
    Message.new channel: "world_channel_#{user_id}", string: msg
  end

  def parse_command(input_string)
    # take in a string of input either from web console or telnet,
    # then compare it against all the users command sets to see if it matches
    # if it does, execute the matching commmand and pass in the args
    # if theres no match send a message to ActionCable saying 'I don't understand what you're trying to do!

    words = input_string.split(' ')
    # try to match the first word.
    first_word = words.first.to_s #
    command = @@player_cmds.cmds.find { |cmd| cmd.keys.include?(first_word) }
    if command
      command.run(self, input_string)
    else
      self.send_message_to_self("I don't understand what you're trying to do!")
    end
  end

end


# todo: make it so that instead of passing strings all the way back to message, input just gets passed to the user,
# then passed to the player, then parsed, then the message gets created. (including a 'i didn't understand command).
# this is far superiour because then we can call commands without making a message, like self.Look

app/models/player/command_set.rb
class Player
  class CommandSet
    attr_accessor :cmds

    def initialize
      @cmds = [LookCommand.new, MoveCommand.new]
    end

    class LookCommand
      attr_accessor :name, :aliases, :callback

      attr_accessor :keys
      def keys
        @aliases.push(@name)
      end

      def initialize
        @is_command = true
        @name = 'look'
        @aliases = ['l']
      end

      # Run Look Command
      def run (player, input)

        # Get title and description of the room
        room = player.current_room
        title = room.title
        desc = room.description

        # Get the actors here
        # actors = Actor.where room_id: self.room_id
        actors = Actor.where room_id: 1
        actors_string = actors.map { |a| "A " + a.name + " is here.\n" }

        player.send_message_to_self([title, desc, actors_string])
      end
    end

    class MoveCommand
      attr_accessor :name, :aliases, :callback

      attr_accessor :keys
      def keys
        @aliases.push(@name)
      end

      def initialize
        @is_command = true
        @name = 'move'
        @aliases = ['m']
      end

      def run (player, input)
        arguments = input.split(' ').drop(1).join
        room = player.current_room
        puts room.exits[arguments]
        if (exit_id = room.exits[arguments])
          player.move_to(exit_id)
        else
          player.send_message_to_self("There is no exit there!")
        end
      end

    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  # has_many :actors_here, foreign_key: "room_id", class_name: "Actor"
  has_many :players_here, foreign_key: "room_id", class_name: "Player"
  # has_many :objects_here, foreign_key: "room_id", class_name: "Object"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_uniqueness_of :email
  has_many :players

  def current_player
    Player.find(self.current_player_id)
  end

  def parse_command(input_string)
    current_player.parse_command(input_string)
  end

end

app/models/world.rb
class World < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render template: 'pages/home'
  end
end

# check this out:
# https://stackoverflow.com/questions/4479233/static-pages-in-ruby-on-rails

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    # puts user.email
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      cookies.encrypted[:user_id] = user.id

      # TODO undo hardcoding of player log in
      # when theres time, this system will support multiple players(characters) per user.
      user.current_player_id = 1

      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      cookies.encrypted[:user_id] = @user.id
      @user.current_player_id = 1
      redirect_to login_path, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  before_action :authorize
  
  def show
    # @messages = Message.all
    @msgs = ["Welcome to the Dark Elf MUD Framework!", "Type help to get started."]
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/application/_flash.html.slim
- flash.each do |type, message|
  ruby:
    case type
    when :notice then flash_class = 'notification is-info'
    when :alert then flash_class = 'notification is-danger'
    else flash_class = 'notification'
    end
  div class="#{flash_class}"
    /button class="delete"
    = message
//javascript:
//  document.querySelectorAll("button.delete").addEventListener("click", function(e) {
//    e.preventDefault();
//    e.target.parentElement().remove();
//  });

app/views/layouts/_nav.html.slim
nav class="navbar is-black"
  div class="navbar-menu"
    div class="navbar-start"
      = link_to 'Home', home_path, class: "navbar-item"
      = link_to 'Play', play_path, class: "navbar-item"
    div class="navbar-end"
      - if current_user
        = link_to "Log Out", logout_path, class: "navbar-item"
      - else
        = link_to "Sign Up", signup_path, class: "navbar-item"
        = link_to "Log In", login_path, class: "navbar-item"

app/views/layouts/application.html.slim
doctype html
html
  head
    title RailsMUD
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render partial: "shared/_nav"
    .container
      = render partial: "shared/_flash", flash: flash
      = yield

app/views/messages/_message.html.slim
.message
  p
    = content

app/views/pages/home.html.slim
section class="section is-white" style="background: white;"
  .column.is-8.is-offset-2
    .container.is-fluid
      h1 class="title is-2 has-text-centered is-spaced" Thank you for checking out the Dark Elf MUD engine
      h4 class="subtitle has-text-centered" View this project on #{link_to 'Github', 'https://github.com/Sevensidedmarble/Dark-Elf-MUD-Framework'}
      hr
      .container.is-fluid
        .content
          p This is a simple MUD (Multi User Dungeon) game engine written in Ruby on Rails. MUDs were a genre of games very popular in the 80s and 90s, in the early days of the internet, but they have fallen off in popularity today.
          p Other MUD engines in Ruby on Rails have existed, but this is the first substantial one I've seen to use the new ActionCable feature in Rails 5. The benefit of using a large framework like Rails for a MUD is that you have access to a single framework that can handle your telnet server, your web client, and the static or near static pages for your MUD like a home page or updates page.
          p This project takes a lot of inspiration from #{link_to 'Evennia', 'https://github.com/evennia/evennia'}, which is a similar engine done in Django.
          p You can click the #{link_to 'Play Now', play_path} link here or above to check out the web client (done in Jquery Terminal) or open up a command prompt on your computer and enter the following command:
          pre telnet dark-elf-mud.herokuapp.com/telnet
          p This will connect to a small little TCP server that runs in an EventMachine loop, that acts as a proxy between ActionCable on the Rails server and your computer via TCP. This is just a simple TCP server right now and doesn't use the advanced features of Telnet or special MUD protocols that allow MUDs to send meta data along with the standard text messages to a client. It would be pretty easy to slot a more complicated server in its place however.

app/views/shared/_flash.html.slim
- flash.each do |type, message|
  ruby:
    case type
    when :notice
      flash_class = 'notification is-info'
    when :alert
      flash_class = 'notification is-danger'
    else
      flash_class = 'notification'
    end
  div class="#{flash_class}"
    button class="delete"
    = message

/ TODO: Work on Javascript for this:
// javascript:
//  document.querySelectorAll("button.delete").addEventListener("click", function(e) {
//    e.preventDefault();
//    e.target.parentElement().remove();
//  });

app/views/shared/_nav.html.slim
nav class="navbar is-black"
  div class="navbar-menu"
    div class="navbar-start"
      = link_to 'Home', home_path, class: "navbar-item"
      = link_to 'Play', play_path, class: "navbar-item"
    div class="navbar-end"
      - if current_user
        = link_to "Log Out", logout_path, class: "navbar-item"
      - else
        = link_to "Sign Up", signup_path, class: "navbar-item"
        = link_to "Log In", login_path, class: "navbar-item"

app/views/users/new.html.slim
section class="section is-white"
  .column.is-8.is-offset-2
    .container.is-fluid
      h1 class="title is-1 has-text-centered"Sign Up
      = form_for @user do |f|
        - if @user.errors.any?
          .error_messages
            h2 class="subtitle is-3" Form is invalid
            ul
              - @user.errors.full_messages.each do |message|
                li class="message" = message
        .field
          = f.label :email, nil, class: 'label'
          .control
            = f.text_field :email, nil, class: 'input'
        .field
          = f.label :password, nil, class: 'label'
          .control
            = f.password_field :password, nil, class: 'input'
        .field
          = f.label :password_confirmation, nil, class: 'label'
          .control
            = f.password_field :password_confirmation, nil, class: 'input'
        .control
          = f.submit "Sign Up", class: "button is-primary"

app/views/worlds/show.html.slim
css:
  body {
    background: #0a0a0a;
  }
.terminal-container
  #terminal